### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by DVanderstoken** [ecteodoro/google-distance-matrix#7]
Fetch API cannot load https://maps.googleapis.com/maps/api/distancematrix/json?origins=-22.255823…nits=metric&language=en&avoid=&key=xxxxxxxxxxxxxxxxxxxxxxxxx.
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://xxxxxxxxx:4200' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

How can I provide needed Headers in the request ?

**Comment by ecteodoro** [comment]
This is how you can add a header to request: https://github.com/request/request#custom-http-headers.
Feel free to fork add headers before this line: https://github.com/ecteodoro/google-distance-matrix/blob/9ff8a2cfab7e5818ee6ce9b82d4a7e06cbe345f2/index.js#L47

**Comment by smykes** [comment]
Any thoughts on this still happening?

**Comment by paladosss** [comment]
May be now any thoughts on this still happening?

**Comment by andrewmcnutt** [comment]
@smykes @paladosss Hello. So the CORS issue is there because (like me probably) you were using this library client side. In short the browser is saying 'hey you are asking for stuff from a different domain'. If you make the call from the server that does not happen. I ended up not using this library after. What I did do was make an XMLHttpRequest(Client side) to a php file(Server side). The XMLHttpRequest was a POST to that file on my server and it worked.

//Client side JS
const vars = 'origin=' + origin +
                 '&destination=' + destination +
                 '&departureTime=' + departureTime +
                 '&apiKey=' + apiKey;
var xhr = new XMLHttpRequest();
    xhr.open('POST', 'path to your file on server.php', true);
    xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
    xhr.onreadystatechange = function() {
         if(xhr.readyState === 4) {
             const responseInfo = JSON.parse(xhr.responseText);
         }
    }
    xhr.send(vars);

//Server side php file
<?php header('Access-Control-Allow-Origin: *'); ?>
<?php
  $url = 'https://maps.googleapis.com/maps/api/distancematrix/json?origins='. urlencode($_POST['origin']) . '&destinations=' . urlencode($_POST['destination']) . '&mode=driving&units=imperial&language=en&avoid=&key=' . $_POST['apiKey'] . '&traffic_model=optimistic&departure_time=' . $_POST['departureTime'];

  // Fetch json response from googleapis.com.
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, $url);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  $response = json_decode(curl_exec($ch), true);

  // Return the response.
  echo json_encode($response);
?>
